### VSCode Extension: REST Client (3.8 M) --- (Đuôi file: .http hoặc .rest)

###! Global variables
@url = http://localhost:6666

###! -------------- Register --------------
POST {{url}}/api/v1/register?hl=vi HTTP/1.1
Content-Type: application/json

{
    "name": "Tester 2",
    "email": "test2@gmail.com",
    "password": "123456"
}

###! -------------- Resend Activation Code --------------
POST {{url}}/api/v1/activate/resend?hl=vi HTTP/1.1
Content-Type: application/json

{
    "email": "test2@gmail.com"
}

###! -------------- Activate --------------
POST {{url}}/api/v1/activate?hl=vi HTTP/1.1
Content-Type: application/json

{
    "activationToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MWFkMzEwMTk3NzZlZWIxOWQ3NmVlNiIsIm90cCI6Ijc5MTE5MyIsImlhdCI6MTY5NjI1NjgxMSwiZXhwIjoxNjk2MjU3MTExfQ._pZtMWS9ohJtavzZYHGroehLyKdhvar8ctmrOCboASI",
    "otp": "791193"
}

###! -------------- Login --------------
# @name login
POST {{url}}/api/v1/login?hl=vi HTTP/1.1
Content-Type: application/json

{
    "email": "einestimono2@gmail.com",
    "password": "123456"
}

###* Tự động gán tokens
@accessToken = {{login.response.body.data.accessToken}}
@refreshToken = {{login.response.body.data.refreshToken}}

###! -------------- Social Auth --------------
# @name social
POST {{url}}/api/v1/social-auth?hl=vi HTTP/1.1
Content-Type: application/json

{
    "email": "socialAuth@gmail.com",
    "name": "Social Auth",
    "avatar": "https://res.cloudinary.com/dtl1pdmw6/image/upload/v1695568685/MegaCine/Default_avatar.png",
    "provider": "Google"
}

###* Tự động gán tokens
# @accessToken = {{social.response.body.data.accessToken}}
# @refreshToken = {{social.response.body.data.refreshToken}}

###! -------------- Refresh Token --------------
# @name refresh
POST {{url}}/api/v1/refresh?hl=vi HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###* Tự động gán tokens
# @accessToken = {{refresh.response.body.data.accessToken}}

###! -------------- Logout --------------
GET {{url}}/api/v1/logout?hl=vi HTTP/1.1
Authorization: Bearer {{accessToken}}

###! -------------- Profile --------------
GET {{url}}/api/v1/me?hl=vi HTTP/1.1
Authorization: Bearer {{accessToken}}

###! -------------- Update user --------------
PUT {{url}}/api/v1/user/me?hl=vi HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary="user content"

--user content
Content-Disposition: form-data; name="name"

Tuệ
--user content
Content-Disposition: form-data; name="phoneNumber"

0987654321
--user content
Content-Disposition: form-data; name="avatar"; filename="Profile.png"
Content-Type: image/png

< C:/Users/Admin/OneDrive/Desktop/ImageProject/Profile.png
--user content--

###! -------------- Update avatar --------------
PUT {{url}}/api/v1/user/avatar?hl=vi HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary="user content"

--user content
Content-Disposition: form-data; name="avatar"; filename="Placeholder.png"
Content-Type: image/png

< C:/Users/Admin/OneDrive/Desktop/ImageProject/Placeholder.png
--user content--

###! -------------- Update password --------------
PUT {{url}}/api/v1/user/password/update?hl=vi HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "oldPassword": "123456789",
    "newPassword": "123456"
}

###! -------------- Forgot password --------------
POST {{url}}/api/v1/password/forgot?hl=vi HTTP/1.1
Content-Type: application/json

{
    "email": "einestimono2@gmail.com"
}

###! -------------- Reset password --------------
PUT {{url}}/api/v1/password/reset?hl=vi HTTP/1.1
Content-Type: application/json

{
    "resetPasswordToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTJlMGFmNDEyZDVjZTU5OGIzOTIwZCIsIm90cCI6IjM5NDc3MyIsImlhdCI6MTY5NjI2MjY2OCwiZXhwIjoxNjk2MjYyOTY4fQ.uOq8oJW_6Snm2qZzbsN7GCFz55GAaT9ird4TxRJZC3E",
    "newPassword": "123456789",
    "otp": "394773"
}