export * from './auth.controller';
export * from './user.controller';
export * from './person.controller';
export * as managerController from './manager.controller';
export * as movieController from './movie.controller';
export * as productController from './product.controller';
export * as uploadController from './upload.controller';
export * as theaterController from './theater.controller';
export * as fareController from './fare.controller';
export * as roomController from './room.controller';
export * as showtimeController from './showtime.controller';
export * as promotionController from './promotion.controller';
export * as reviewController from './review.controller';
