export * as userServices from './user.service';
export * as cloudinaryServices from './cloudinary.service';
export * as genreServices from './genre.service';
export * as personServices from './person.service';
export * as managerServices from './manager.service';
export * as movieServices from './movie.service';
export * as productServices from './product.service';
export * as theaterServices from './theater.service';
export * as fareServices from './fare.service';
