export const ENDPOINTS = {
  LOGIN: '/manager/login',
  LOGOUT: '/logout',
  SIGNUP: '/manager/register',
  LIST_USER: '/user/list',
  TOGGLE_BLOCK_USER: '/user/toggle-block',
  APPROVAL_LIST_MANAGER: '/manager/approval-list',
  MANAGER_DETAILS: '/manager/details',
  LIST_MANAGER: '/manager/list',
  ACTIVATE_MANAGER: '/manager/activate',
  DELETE_MANAGER: '/manager/details',
  LISTMOVIE: '/movie/list',
  UPLOADFILE: '/upload/image',
  UPLOADFILES: '/upload/images',
  LIST_GENRE: '/genre/list',
  CREATE_GENRE: '/genre/create',
  GENRE_DETAILS: '/genre/details',
  LIST_PEOPLE: '/person/list',
  CREATE_PEOPLE: '/person/create',
  PEOPLE_DETAILS: '/person/details',
};
