export const ENDPOINTS = {
  LOGIN: '/manager/login',
  LOGOUT: '/logout',
  LIST_USER: '/user/list',
  TOGGLE_BLOCK_USER: '/user/toggle-block',
  APPROVAL_LIST_MANAGER: '/manager/approval-list',
  MANAGER_DETAILS: '/manager/details',
  LIST_MANAGER: '/manager/list',
  ACTIVATE_MANAGER: '/manager/activate',
  DELETE_MANAGER: '/manager/details',
  LISTMOVIE: '/movie/list',
  LIST_GENRES: '/genre/list',
  CREATE_GENRES: '/genre/create',
  LIST_PERSON: '/person/list',
  UPLOADFILE: '/upload/image',
  UPLOADFILES: '/upload/images',
  SIGNUP: '/manager/register',
  CREATE_MOVIE: '/movie/create',
  MOVIE_NOW_SHOWING: '/movie/now-showing',
  MOVIE_COMING_SOON: '/movie/coming-soon',
  MOVIE_DETAILS: '/movie/details/:id',
  MOVIE_SNEAK_SHOW: '/movie/sneak-show',
  MOVIE_MOST_RATE: '/movie/most-rate',
  REFRESH_TOKEN: '/refresh',
};
