name: Server CI

on:
    push:
        branches: ["main", "develop"]
        paths: ["server/**"]
    pull_request:
        branches: ["main", "develop"]
        paths: ["server/**"]
    workflow_dispatch:

jobs:
    test:
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        defaults:
            run:
                working-directory: server
        steps:
            - name: SERVER - Checkout repository
              uses: actions/checkout@v4

            - name: SERVER - Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
                  cache-dependency-path: "./server/yarn.lock"

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-server-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-server-

            - name: SERVER - Install dependencies
              run: yarn --frozen-lockfile

            - name: SERVER - Lint check
              run: yarn lint
